# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 329fcdd389231705888c18bd1f271598096150aa4b0a6a9aa29d2a43680a8728cb56f7e257cb39e175c532f522af5f257b64b6f9af9bd592a5869fb0ab482a6b

test:
  secret_key_base: 0ad3f6fb91ea0030db2aeba86146bc97fabbbf94e65236fd7c657b42b0cd426fe33827a5fb794327ed693b5e4a181f53340f61dcd67797083b73879731559ce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
